# Practise During Class

# Numpy

In [2]:
import numpy as np
arr = np.array(12)
print(arr)
print(arr.ndim)

12
0

In [3]:
import numpy as np
arr = np.array([1,2,3,4,5], ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4 5]]]]]
5

In [4]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[0])

1

In [6]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])

6

In [7]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr[1:5])

[2 3 4 5]

In [8]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[:4])

[1 2 3 4]

In [11]:
# Stepping with slicing
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[1::2])

[2 4 6 8]

In [12]:
# Stepping with slicing
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[1:8:2])

[2 4 6 8]

In [13]:
import numpy as np
arr = np.array([1,2,3,4,5,6], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5' b'6']
|S1

In [ ]:
import numpy as np
arr = np.array([1.1,2.1,3.1])
farr = arr.astype('i')

print(arr)
print(farr)

[1.1 2.1 3.1]
[1 2 3]

In [ ]:
# tells rows and columns (shape of the array)
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)

In [21]:
# reshaping the array but if it exceeds the elements it will give error
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(arr)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

In [ ]:
# iterating numpy arrays
import numpy as np
arr = np.array([1,2,3,4,5,6])
for x in arr:
    print(x, end=" ")

1 2 3 4 5 6

In [31]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
    for y in x:
        print(y, end=" ")

1 2 3 4 5 6

In [35]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    for y in x:
        for z in y:
            print(z, end=" ")

1 2 3 4 5 6 7 8 9 10 11 12

In [38]:
# nditer method is used to access each element of multidimentional array in a single loop
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in np.nditer(arr):
    print(x, end=" ")

1 2 3 4 5 6 7 8 9 10 11 12

In [42]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
newarr = np.array(np.array_split(arr,3))
print(newarr)
print(newarr.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)

In [45]:
# split train and test data
from numpy import array
# define array
data = array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])
# separate data
split = 2
train,test = data[:split,:],data[split:,:]
print("Train:",train)
print("Test:",test)

Train: [[11 22 33]
 [44 55 66]]
Test: [[77 88 99]]

# Pandas

In [46]:
import pandas as pd
print(pd.__version__)

3.0.0

In [55]:
import pandas as pd
mydataset = {
    "Cars": ["BMW", "Suzuki", "Ford","Toyota", "Nissan", "Lamborghini"],
    "Passings": [4,2,6,3,8,9]
}
df = pd.DataFrame(mydataset)
print(df)

          Cars  Passings
0          BMW         4
1       Suzuki         2
2         Ford         6
3       Toyota         3
4       Nissan         8
5  Lamborghini         9

In [53]:
# .head() function is used to access/view the first five records/rows of the dataset
import pandas as pd
mydataset = {
    "Cars": ["BMW", "Suzuki", "Ford","Toyota", "Nissan", "Lamborghini"],
    "Passings": [4,2,6,3,8,9]
}
df = pd.DataFrame(mydataset)
df.head()

     Cars  Passings
0     BMW         4
1  Suzuki         2
2    Ford         6
3  Toyota         3
4  Nissan         8

In [56]:
import pandas as pd
a = [41,43,12]
b = pd.Series(a)
print(b)

0    41
1    43
2    12
dtype: int64

In [58]:
import pandas as pd
a = [41,43,12]
b = pd.Series(a, index = ["a","b", "c"])
print(b)
print(b["a"])

a    41
b    43
c    12
dtype: int64
41

In [60]:
import pandas as pd
calories = {"Day1": 12, "Day2": 13, "Day3": 14}
abc = pd.Series(calories)
print(abc)

Day1    12
Day2    13
Day3    14
dtype: int64

In [61]:
import pandas as pd
calories = {"Day1": 12, "Day2": 13, "Day3": 14}
abc = pd.Series(calories, index = ["Day1", "Day2"])
print(abc)

Day1    12
Day2    13
dtype: int64

In [62]:
import pandas as pd
data = {
    "calories": [210,432,780],
    "duration": [20,30,40]
}
a = pd.DataFrame(data)
print(a)

   calories  duration
0       210        20
1       432        30
2       780        40

In [69]:
# .loc[] function is used to access any row
import pandas as pd
data = {
    "calories": [210,432,780],
    "duration": [20,30,40]
}
df = pd.DataFrame(data)
print(df.loc[0])

calories    210
duration     20
Name: 0, dtype: int64

In [68]:
# List of indexes to locate multiple rows
import pandas as pd
data = {
    "calories": [210,432,780],
    "duration": [20,30,40]
}
df = pd.DataFrame(data)
print(df.loc[[0, 1]])

   calories  duration
0       210        20
1       432        30

In [72]:
# giving each row a name and accessing that row by that specific index/name in .loc[] function
import pandas as pd
data = {
    "calories": [210,432,780],
    "duration": [20,30,40]
}
df = pd.DataFrame(data, index = ["Day1", "Day2", "Day3"])
print(df)
print("first row only:",df.loc["Day1"])

      calories  duration
Day1       210        20
Day2       432        30
Day3       780        40
first row only: calories    210
duration     20
Name: Day1, dtype: int64

# Analyzing Datasets/DataFrames in Pandas Library

In [ ]:
# Loading a dataset into DataFrame
import pandas as pd
path = r"C:\Users\User\Downloads\Students Social Media Addiction.csv"
df = pd.read_csv(path)
df.head()

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
0,1,19,Female,Undergraduate,Bangladesh,5.2,Instagram,Yes,6.5,6,In Relationship,3,8
1,2,22,Male,Graduate,India,2.1,Twitter,No,7.5,8,Single,0,3
2,3,20,Female,Undergraduate,USA,6.0,TikTok,Yes,5.0,5,Complicated,4,9
3,4,18,Male,High School,UK,3.0,YouTube,No,7.0,7,Single,1,4
4,5,21,Male,Graduate,Canada,4.5,Facebook,Yes,6.0,6,In Relationship,2,7

In [ ]:
# tail method shows the last 5 rows of the dataset
import pandas as pd
path = r"C:\Users\User\Downloads\Students Social Media Addiction.csv"
df = pd.read_csv(path)
df.tail()

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
700,701,20,Female,Undergraduate,Italy,4.7,TikTok,No,7.2,7,In Relationship,2,5
701,702,23,Male,Graduate,Russia,6.8,Instagram,Yes,5.9,4,Single,5,9
702,703,21,Female,Undergraduate,China,5.6,WeChat,Yes,6.7,6,In Relationship,3,7
703,704,24,Male,Graduate,Japan,4.3,Twitter,No,7.5,8,Single,2,4
704,705,19,Female,Undergraduate,Poland,6.2,Facebook,Yes,6.3,5,Single,4,8

In [3]:
# info method shows information of dataset like how many non null values there are in each column
import pandas as pd
path = r"C:\Users\User\Downloads\Students Social Media Addiction.csv"
df = pd.read_csv(path)
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 705 entries, 0 to 704
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Student_ID                    705 non-null    int64
 1   Age                           705 non-null    int64
 2   Gender                        705 non-null    str
 3   Academic_Level                705 non-null    str
 4   Country                       705 non-null    str
 5   Avg_Daily_Usage_Hours         705 non-null    float64
 6   Most_Used_Platform            705 non-null    str
 7   Affects_Academic_Performance  705 non-null    str
 8   Sleep_Hours_Per_Night         705 non-null    float64
 9   Mental_Health_Score           705 non-null    int64
 10  Relationship_Status           705 non-null    str
 11  Conflicts_Over_Social_Media   705 non-null    int64
 12  Addicted_Score                705 non-null    int64
dtypes: float64(2), int64(5), str(6)
memory usage: 71.7 KB
None

# Data Cleaning in Pandas

In [8]:
# df.isnull().sum() counts missing values per column
# df.isnull().sum().sum() counts total missing values in dataset
import pandas as pd
path = r"C:\Users\User\Downloads\Students Social Media Addiction.csv"
df = pd.read_csv(path)
print(df.isnull().sum())
print("Total missing values in dataset: ",df.isnull().sum().sum())

Student_ID                      0
Age                             0
Gender                          0
Academic_Level                  0
Country                         0
Avg_Daily_Usage_Hours           0
Most_Used_Platform              0
Affects_Academic_Performance    0
Sleep_Hours_Per_Night           0
Mental_Health_Score             0
Relationship_Status             0
Conflicts_Over_Social_Media     0
Addicted_Score                  0
dtype: int64
Total missing values in dataset:  0

In [10]:
# dropna() method is used to remove empty rows
# inside dropna we write inplace = True to modify the dataframe without creating its copy
import pandas as pd
path = r"C:\Users\User\Downloads\Students Social Media Addiction.csv"
df = pd.read_csv(path)
df.dropna(inplace=True)

In [ ]:
# if we use fillna method like this it will work on copy not the actual dataframe
import pandas as pd

data = {
    "calories": [210, 432, None],
    "duration": [20, 30, 40]
}

df = pd.DataFrame(data, index=["Day1", "Day2", "Day3"])
print(df.isnull())

df["calories"].fillna(130, inplace=True)

      calories  duration
Day1     False     False
Day2     False     False
Day3      True     False

C:\Users\User\AppData\Local\Temp\ipykernel_22084\1572858294.py:11: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["calories"].fillna(130, inplace=True)

Day1    210.0
Day2    432.0
Day3    130.0
Name: calories, dtype: float64

In [ ]:
# .fillna(value, inplace = True) method replaces all empty cells in the whole Data Frame with that given value
# in this way we are working on actual dataframe
import pandas as pd

data = {
    "calories": [210, 432, None],
    "duration": [20, 30, 40]
}

df = pd.DataFrame(data, index=["Day1", "Day2", "Day3"])
print(df.isnull())

df.fillna({"calories": 130}, inplace=True)

      calories  duration
Day1     False     False
Day2     False     False
Day3      True     False

      calories  duration
Day1     210.0        20
Day2     432.0        30
Day3     130.0        40

In [25]:
# Correcting the Wrong Data by replacing the value
import pandas as pd
data = {
    "calories": [210, 432, 340],
    "duration": [20, 30, 40]
}

df = pd.DataFrame(data, index=["Day1", "Day2", "Day3"])

for x in df.index:
    if df.loc[x, 'duration'] > 30:
        df.loc[x, 'duration'] = 30
print(df)

      calories  duration
Day1       210        20
Day2       432        30
Day3       340        30

In [ ]:
#.duplicated() method returns True for every row that is duplicate, otherwise false
#.drop_duplicates(inplace=True) method is used to remove duplicated rows from original df
import pandas as pd
data = {
    "calories": [210, 30, 30],
    "duration": [20, 30, 30]
}

df = pd.DataFrame(data, index=["Day1", "Day2", "Day3"])

print("Duplicated row:\n",df.duplicated())

df.drop_duplicates(inplace=True)
print("After removing duplicates:\n",df)

Duplicated row:
 Day1    False
Day2    False
Day3     True
dtype: bool
After removing duplicates:
       calories  duration
Day1       210        20
Day2        30        30